spring:
  application:
    name: app-module
  spring:
    config:
      import: "classpath:application-infra.yml, classpath:application-common.yml, classpath:application-core.yml"

  datasource:
    url: jdbc:mysql://localhost:3306/ticketing
    username: root
    password: aA23372381!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
